// Generated by scripts/sync-vehicle-catalog.cjs.
import type {ImageSourcePropType} from "react-native";
import type {ActiveVehicleKind} from "@pepo/types/model";
export const MAP_VEHICLE_IMAGES: Partial<Record<ActiveVehicleKind, ImageSourcePropType>> = {
  moto: require("../assets/vehicles/moto-top.png"),
  motoSend: require("../assets/vehicles/moto-top.png"),
  taxi: require("../assets/vehicles/car-top.png"),
  suv: require("../assets/vehicles/catalog/suv.png"),
  minibus: require("../assets/vehicles/catalog/minibus.png"),
  tricycle: require("../assets/vehicles/catalog/tricycle.png"),
  truck: require("../assets/vehicles/catalog/camion.png"),
  pickupTruck: require("../assets/vehicles/catalog/pick-up truck.png"),
};
