// Generated by scripts/sync-vehicle-catalog.cjs. Add your PNGs and restart Metro.
import type {ImageSourcePropType} from "react-native";
import type {VehicleKind} from "@pepo/types/model";
export const VEHICLE_IMAGES: Partial<Record<VehicleKind, ImageSourcePropType>> = {
  moto: require("../assets/vehicles/catalog/moto.png"),
  comfort: require("../assets/vehicles/catalog/moto.png"),
  taxi: require("../assets/vehicles/catalog/taxi.png"),
  suv: require("../assets/vehicles/catalog/suv.png"),
  minibus: require("../assets/vehicles/catalog/minibus.png"),
  tricycle: require("../assets/vehicles/catalog/tricycle.png"),
  truck: require("../assets/vehicles/catalog/camion.png"),
  pickupTruck: require("../assets/vehicles/catalog/pick-up truck.png"),
};
